# Generated by Django 6.0.5 on 2026-05-22 00:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('adotante', 'Adotante'), ('ong', 'ONG/Resgatador')], default='adotante', max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_moradia', models.CharField(blank=True, choices=[('apt', 'Apartamento'), ('house-yard', 'Casa com quintal'), ('house', 'Casa sem quintal'), ('other', 'Outro')], max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('moradores', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adotante_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ong', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ong_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=10)),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20)),
                ('idade_texto', models.CharField(help_text='Ex: 2 anos, 6 meses', max_length=50)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10)),
                ('raca', models.CharField(default='SRD', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('vacinado', models.BooleanField(default=False)),
                ('castrado', models.BooleanField(default=False)),
                ('vermifugado', models.BooleanField(default=False)),
                ('microchip', models.BooleanField(default=False)),
                ('amigo_criancas', models.BooleanField(default=False)),
                ('amigo_outros_pets', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('analise', 'Em análise'), ('lar_temporario', 'Lar temporário'), ('adotado', 'Adotado')], default='disponivel', max_length=20)),
                ('imagem_emoji', models.CharField(default='🐶', max_length=10)),
                ('cor_fundo', models.CharField(default='bg-pink', help_text='Classe CSS de cor. Ex: bg-pink, bg-peach, bg-blue, etc', max_length=20)),
                ('urgente', models.BooleanField(default=False)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.ong')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entrevista', 'Em Entrevista'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('motivo_recusa', models.TextField(blank=True, null=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.adotante')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.adotante')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritados', to='core.pet')),
            ],
            options={
                'unique_together': {('adotante', 'pet')},
            },
        ),
    ]
