# Generated by Django 6.0.5 on 2026-06-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=300)),
                ('imagem', models.CharField(default='🤝', help_text='URL da imagem ou emoji', max_length=200)),
                ('link_externo', models.URLField()),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
