# Generated by Django 6.0.5 on 2026-06-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade_recomendada', models.CharField(help_text='Ex: 2 meses, 1 ano', max_length=100)),
                ('periodicidade', models.CharField(blank=True, help_text='Ex: Anual, Única dose', max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('ambos', 'Cão e Gato')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['especie', 'idade_recomendada'],
            },
        ),
        migrations.AddField(
            model_name='ong',
            name='maps_url',
            field=models.URLField(blank=True, help_text='URL do Google Maps Embed (ex: https://maps.google.com/maps?q=...)', null=True),
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.pet')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
